apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rt-files-pvc
  namespace: rtorrent-x
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 70Ti
  volumeName: "rt-main-files-pv"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: rt-main-files-pv
spec:
  storageClassName: nfs-client
  capacity:
    storage: 70Ti
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /srv/nfs/raid6/
    server: 192.168.50.57
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: rt-main-data-pv
spec:
  storageClassName: nfs-client
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /srv/nfs/raid6/rt/data/
    server: 192.168.50.57
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rt-data-pvc
  namespace: rtorrent-x
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: "rt-main-data-pv"
---
