apiVersion: v1
kind: Service
metadata:
  name: rtorrent-main-internal
  namespace: rtorrent-x
  labels:
    app: rtorrent-main
spec:
  type: ClusterIP
  ports:
    - port: 8000
      protocol: TCP
      name: "xmlrpc"
    - port: 9000
      protocol: TCP
      name: "webdav"
  selector:
    app: rtorrent-main
