apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: docker-registry-certificate
  namespace: kube-system
spec:
  commonName: registry.s8njee.com
  secretName: docker-tls-secret
  duration: 2160h
  renewBefore: 72h
  subject:
    organizations:
      - s8njee
  dnsNames:
    - registry.s8njee.com
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: "letsencrypt-prod"
    kind: Issuer
    group: cert-manager.io
