apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-reader
  namespace: security-demo
automountServiceAccountToken: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: app-reader
  namespace: security-demo
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - configmaps
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: app-reader
  namespace: security-demo
subjects:
  - kind: ServiceAccount
    name: app-reader
    namespace: security-demo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: app-reader
