apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0001 
spec:
  storageClassName: nfs-client
  capacity:
    storage: 20Gi 
  accessModes:
  - ReadWriteOnce
  nfs: 
    path: /srv/nfs/raid6/k8sPVs
    server: 192.168.0.212
  persistentVolumeReclaimPolicy: Retain 
