apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv-nfs
spec:
  capacity:
    storage: 40Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-csi
  mountOptions:
    - nfsvers=4.1
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: postgres-pv-nfs
    volumeAttributes:
      server: 192.168.1.204
      share: /srv/nfs/raid6/k8sPVs
