apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-claim
  namespace: postgres
spec:
  storageClassName: nfs-csi
  volumeName: postgres-pv-nfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 40Gi
